<a href="https://colab.research.google.com/github/adikiit123/SharpML/blob/master/spamModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import io
from keras.layers import Dense,Embedding,Flatten,LSTM
from keras.models import Sequential
from keras.preprocessing import sequence
from keras.losses import binary_crossentropy
from keras.optimizers import SGD
from keras.preprocessing.text import Tokenizer
from google.colab import files


uploaded = files.upload()
spamData = pd.read_csv(io.StringIO(uploaded['SpamMails.csv'].decode('utf-8')))

X = spamData['Text']
Y = spamData['Class']

xTrain = []
yTrain = []

# Encoding the Text as Binary Outputs
for i, label in enumerate(spamData['Class']):
    xTrain.append(spamData['Text'][i])
    if label == 'ham':
        yTrain.append(1)
    elif label == 'spam':
        yTrain.append(0)


xTrain = np.asarray(xTrain)
yTrain = np.asarray(yTrain)
  
        
trainTokenizerInstance = Tokenizer()
trainTokenizerInstance.fit_on_texts(xTrain)
encodedTrainTextVector = trainTokenizerInstance.texts_to_sequences(xTrain)

maxVectorLength = 500
vocabSize = 10000

print("Vector Dimension : {0}".format(maxVectorLength))
print("Vocab Size : {0}".format(vocabSize))

paddedWord2Vec = sequence.pad_sequences(encodedTrainTextVector,maxVectorLength)

print(paddedWord2Vec)

spamDetectorModel = Sequential()
word2VecEmbedding = Embedding(vocabSize,32)
lstmLayer = LSTM(32)
outputLayer = Dense(1,activation = 'sigmoid')

spamDetectorModel.add(word2VecEmbedding)
spamDetectorModel.add(lstmLayer)
spamDetectorModel.add(outputLayer)

sgdOptimizer = SGD(0.01,0.4,0.01,True)

spamDetectorModel.compile(sgdOptimizer,loss = binary_crossentropy,metrics = ['accuracy'])
spamDetectorModel.fit(paddedWord2Vec,yTrain,100,5)
spamDetectorModel.save("SpamModel.md5")














Saving SpamMails.csv to SpamMails (3).csv
Vector Dimension : 500
Vocab Size : 10000
[[   0    0    0 ...   58 4427  144]
 [   0    0    0 ...  472    6 1940]
 [   0    0    0 ...  659  391 2994]
 ...
 [   0    0    0 ...  107  250 9005]
 [   0    0    0 ...  198   12   47]
 [   0    0    0 ...    2   61  267]]
Epoch 1/5
5572/5572 [==============================] - 22s 4ms/step - loss: 0.5971 - acc: 0.8600
Epoch 2/5
5572/5572 [==============================] - 22s 4ms/step - loss: 0.4967 - acc: 0.8659
Epoch 3/5
5572/5572 [==============================] - 21s 4ms/step - loss: 0.4544 - acc: 0.8659
Epoch 4/5
5572/5572 [==============================] - 21s 4ms/step - loss: 0.4326 - acc: 0.8659
Epoch 5/5
5572/5572 [==============================] - 21s 4ms/step - loss: 0.4200 - acc: 0.8659
